name: Run cargo-msrv

on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    branches: ["dev"]
    
jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@550686d15d352594247b588987fa8a399dc2bd55 # main

