name: Publish

on:
  push:
    tags: ["**"]
  workflow_dispatch:

env:
  # renovate: datasource=github-tags depName=rust-lang/rust versioning=rust-release-channel
  RUST_VERSION: 1.94.1

jobs:
  changelog-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      with:
        toolchain: ${{ env.RUST_VERSION }}

    - id: version
      run: echo "version=v$(cargo pkgid | cut -d '#' -f 2)" >> "$GITHUB_OUTPUT"
    - id: changelog
      run: |
        {
          echo 'changelog<<__EOF__'
          python -c "
        import os
        version = os.environ['VERSION']
        print('\n'.join(open('CHANGELOG.md').read().split('## '+version)[1].split('\n')[1:]).split('\n##')[0])
          "
          echo __EOF__
        } >> "$GITHUB_OUTPUT"
      env:
        VERSION: ${{ steps.version.outputs.version }}

  build: # adapted from https://github.com/foresterre/cargo-msrv/blob/main/.github/workflows/build-release-binaries.yaml
    runs-on: ${{ matrix.os }}
    needs: changelog-version
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive_ext: tgz
            kind: linux

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            archive_ext: tgz
            kind: linux

          - target: x86_64-apple-darwin
            os: macos-15-intel
            archive_ext: tgz
            kind: macos

          - target: aarch64-apple-darwin
            os: macos-latest
            archive_ext: tgz
            kind: macos

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive_ext: zip
            kind: windows

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      with:
        toolchain: ${{ env.RUST_VERSION }}
        target: ${{ matrix.target }}

    - shell: bash
      run: |
        echo "archive=flight-network-planner-${{ matrix.target }}-${{ needs.changelog-version.outputs.version }}.${{ matrix.archive_ext }}" >> "$GITHUB_ENV"
        echo "subfolder=flight-network-planner-${{ matrix.target }}-${{ needs.changelog-version.outputs.version }}" >> "$GITHUB_ENV"
    - shell: bash
      run: mkdir ${{ env.subfolder }}

    - if: matrix.target == 'x86_64-unknown-linux-musl'
      uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
      env:
        # renovate: datasource=deb depName=musl-tools
        MUSL_TOOLS_VERSION: 1.2.4-2
      with:
        packages: musl-tools=${{ env.MUSL_TOOLS_VERSION }}
        version: 1.0

    - shell: bash
      run: cargo build --locked --target=${{ matrix.target }} --release
      
    - if: matrix.kind == 'macos'
      shell: bash
      run: |
        cp target/${{ matrix.target }}/release/flight-network-planner ${{ env.subfolder }}
        gtar --create --gzip --file=${{ env.archive }} ${{ env.subfolder }}
    - if: matrix.kind == 'linux'
      shell: bash
      run: |
        cp target/${{ matrix.target }}/release/flight-network-planner ${{ env.subfolder }}
        tar --create --gzip --file=${{ env.archive }} ${{ env.subfolder }}
    - if: matrix.kind == 'windows'
      shell: bash
      run: |
        cp target/${{ matrix.target }}/release/flight-network-planner.exe ./${{ env.subfolder }}
        7z a -tzip ${{ env.archive }} ${{ env.subfolder }}
    
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ matrix.target }}
        path: ./${{ env.archive }}

  github-release:
    runs-on: ubuntu-latest
    needs: [build, changelog-version]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - run: cargo package --locked
      - run: mkdir dist
      - run: mv target/package/*.crate dist

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: x86_64-unknown-linux-gnu
          path: dist
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: x86_64-unknown-linux-musl
          path: dist
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: x86_64-apple-darwin
          path: dist
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: aarch64-apple-darwin
          path: dist
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: x86_64-pc-windows-msvc
          path: dist

      - uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          body: ${{ needs.changelog-version.outputs.changelog }}
          tag_name: ${{ needs.changelog-version.outputs.version }}
          files: dist/*

  crates-io:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: crates
      url: https://crates.io/crates/flight-network-planner
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe # v1.0.4
        id: auth
      - run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  delete-github-release:
    runs-on: ubuntu-latest
    needs: [ changelog-version, build, github-release, crates-io ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: gh release delete "$TAG" --cleanup-tag -y
        env:
          TAG: ${{ needs.changelog-version.outputs.version }}
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
